name: Seller
main: com.Moon_Eclipse.Seller.Seller
version: 1.1
author: Moon_Eclipse
commands:
    팔기:
        description: /팔기 일반 코드 메타 가격 수량
                     /팔기 이름 코드 메타 디스플레이이름 가격 수량
                     /팔기 교환 코드 메타 디스플레이이름 수량 교환할아이템
                     /팔기 무시 코드 0 디스플레이이름 가격 수량
                     /팔기 교환2 코드1 메타1 디스플레이이름1 수량1 코드2 메타2 디스플레이이름2 수량2 교환할아이템이름
permissions:
    seller.*:
        description: 셀러 플러그인의 모든 권한을 갖습니다.
        default: op
    seller.sell:
        description: 셀러 플러그인의 기능을 사용할 권한을 갖습니다.
        default: op